### ISSUE TITLE
Decoding Gaze Data

### ISSUE THREAD

**Issue by kniv0gaffel** [pupil-labs/pupil-docs#700]
Hi, I am working on an application which requires me to implement my own client in C++ for the NEON gaze tracking goggles. 
I am following this guide https://pupil-labs-realtime-api.readthedocs.io/en/latest/guides/under-the-hood.html#decoding-gaze-data
but I am a little stuck when it comes to decoding the data. Compared to the python implementation my data is scaled and biased differently. I found the guide a little lacking in this department, for instance, nowhere does it say what in what units the measurements are, or if and how the measurements need to be preprocessed using the other fields (like optical axis and center).
I hope you can help me with this

**Comment by rennis250** [comment]
Hi @kniv0gaffel ,

as mentioned at that link, the units are pixels, expressed in the coordinate system of the scene camera image, and encoded at 32-bit floats:

https://docs.pupil-labs.com/neon/data-collection/data-streams/#gaze

If you are trying to overlay gaze on the scene camera image, then the values do not need to be scaled nor biased and you do not need to pre-process other fields.

The values are the same as what is used in the Python implementation to overlay gaze on the scene camera video, for example:

https://docs.pupil-labs.com/neon/real-time-api/tutorials/#scene-video-and-gaze-pupil-diameter-and-eye-state-data

The first 9 bytes of the gaze datum in the RTP packet have not changed, so my first guess would be that there is an issue with type conversion in the C++ code. Perhaps wrong Endian order was used? That at least happened to me when I first played around the RTCP stream.

For reference, here is how I have done it when experimenting in Go:

```go
x := math.Float32frombits(binary.BigEndian.Uint32(pkt.Payload[0:4])) // first 4 bytes are gaze x
y := math.Float32frombits(binary.BigEndian.Uint32(pkt.Payload[4:8])) // next 4 bytes are gaze y
worn := pkt.Payload[8] // 9th byte is worn, which is currently always 255 (i.e., true) for Neon
```

I just tried it again and it works as expected. Also:

- When you gaze in the top left corner of the scene camera image, then `gaze (x, y) => (0 pixels, 0 pixels)`
- When you gaze in the bottom right corner of the scene camera image, then `gaze (x, y) => (1600 pixels, 1200 pixels)`
- When you gaze in the center of the scene camera image, then `gaze (x, y) => (800 pixels, 600 pixels)`

Since the docs are fine in this case, and this is an implementation issue specific to another codebase, I will close this, if that is alright with you.

If you are okay with it, we can continue communication on our Discord server, which is intended for such questions:

https://pupil-labs.com/chat

You can post your question in the #software-dev channel and get faster feedback from us.

Best regards,
Rob
