### ISSUE TITLE
Missing section about 3d mapping

### ISSUE THREAD

**Issue by papr** [pupil-labs/pupil-docs#71]

**Comment by nathakits** [comment]
@papr - is this the missing section?

> Let's take a closer look at the `General` sub-menu.
> 
> ![world-sidebar-callout](https://user-images.githubusercontent.com/17331040/28603774-6c2d7cee-71f0-11e7-80af-ac31b1940a4c.png)
> 
>   1. **Detection and mapping mode** - you can select `2d` or `3d` detection and mapping mode. Read more about the differences here (to come.).
>   1. **Detect eye0** and **Detect eye1** - these toggled buttons launch and stop eye processes in a new `Eye` window. Your selection will be saved for the next time `Pupil Capture` is opened.
>   1. **Open plugin** - select a plugin from the drop down list. A plugin sub-menu will be added to the GUI with (optional) hot key. Read more about Pupil Capture plugins [here](https://github.com/pupil-labs/pupil/wiki/Plugin-Guide).

**Comment by papr** [comment]
No, missing in the sense that we need one, not in the sense, that it existed once but is gone now. This section should include information about the 3d eye model, the bundle adjustment procedure and the vector gaze mapper. But this can wait until @KD has finished the documentation on his work.

**Comment by behinger** [comment]
I just wanted to comment on this because I found it a bit confusing and it might help others:
The 2D and 3D are used twice for different things.

Pupil detection:
2D - basically ellipse center detection, later mapped to the calibrated screen
3D - a 3D model of the eye is estimated (that is the green circle/sphere in the eye-screen). In principle needs only 3 points of calibration (if I'm correct), but more can be used

Calibration:
2D - polynomial mapping. You need to estimate a 2D function that maps f(eyeX,eyeY) to g(worldX,worldY). Pupillabs uses (afaik) 13 parameters (X, Y, X^2, Y^2, XY, X^2Y^2, ...) to do this mapping based on the calibration data
3D - bundle adjustment calibration - I don't know much about this algorithm (is it doing calibration in actual 3D space? How would it account for parallax?)

Thanks for a short comment/confirmation/correction :)

**Comment by willpatera** [comment]
Closing; stale. 3d mapping is documented via paper published by Dierkes et al.
