### ISSUE TITLE
What exactly is audio_timestamps.npy

### ISSUE THREAD

**Issue by pasbi** [pupil-labs/pupil-docs#73]
sure, it contains timestamps and it looks like they are produced using the same clock as e.g. `world_timestamps.npy` or `world_timestamps.npy`.
But, how do I find out how to cut  `audio.wav` that fits to a `world.mp4`-snippet from e.g. 02:12:10 to 02:12:40?

I have a 4:32:01h `audio.wav`, and there are `12241158` entries in the `audio_timestamps.npy`-file.
That means roughly 720 entries per second, but `audio.wav` is sampled with 48kHz.

Yes, I could follow [the docs](https://github.com/pupil-labs/pupil-docs/blob/master/user-docs/pupil-capture.md#audio-capture) and use `pupil-player` to export the video and mux it, then cut the video and eventually demux it, however, I'd prefer to keep video and audio separated all the time.

**Comment by papr** [comment]
@pasbi We are currently changing the content of `audio_timestamps.npy` in order to simplify our avsync feature. I will add documentation as soon as we merge it.

**Comment by pasbi** [comment]
That's good news, however, I'd like to use it now :grin: 
Is there any simple way to achieve my goal?
Maybe I should have posted this issue in the pupil repo : thinking:

**Comment by papr** [comment]
No, this is an documentation issue. It is perfectly placed.

Audio samples are grouped by audio frames. Live stream audio frames are usually small (~64 samples/frame) to reduce latency. When reading from file audio frames are usually bigger, e.g. 1024 samples/frame). Previously, we stored a timestamp for each incoming audio frame. This is why you have ~720 entries per second: 48k / 720 is roughly 66.

In the new `avsync` branch, we transcode the incoming audio to the `aac` format and calculate timestamps for every encoded audio frame (containing ~1024 samples/frame).

This means that you have to demux all audio frames from the `audio.mp4` file to correlate them with their corresponding timestamps. This is consistent to how we handle video. Unfortunately, it is not possible to assign the correct PTS during encoding since we get less (bigger) packets out than we put into the encoder and the encoder is not able to keep track of the PTS :( for us.

You could write yourself an audio export plugin that mirrors the [`av_writer`s](https://github.com/papr/pupil/blob/avsync/pupil_src/shared_modules/av_writer.py#L161-L178) audio muxing capabilities but does not export video. Then you could use the trim marks to specify on a per-frame-basis which audio to export.

Check out the `avsync` branch and open previous recordings to convert them to the new format.

**Comment by pasbi** [comment]
Thanks for your explanations! However, that sounds rather complicated.
I'm going to mux video and audio in `pupil_player`, cut the video using `ffmpeg` and demux audio and video again, that should be fine.

**Comment by pasbi** [comment]
If I use `world.mp4`, I need `world_timestamps.npy` in order to convert real-time to world-time.
What if I use the video that `pupil_player` exports, i.e. `world_viz.mp4`? Can I assume that it uses real-time or do I also need to convert timestamps using `world_timestamps.npy`?

**Comment by papr** [comment]
The `world_timestamps.npy` are the real timestamps on which each frame was recorded. The `world.mp4` video file's PTS (presentation timestamps) are evenly spaced to simplify seeking. The `world_viz.mp4` PTS are spaced such that it corresponds their actual recording time as saved in `world_timestamps.npy`.

**Comment by pasbi** [comment]
Ok, just to be 100% sure that I got you right:
Imagine I start a stopwatch exactly when I press record in `pupil_capture`, then I look at the watch for 1h and stop the recording after that, export the `world_viz.mp4` and watch it.
Will the time be shown on the watch be the same as the time shown in my video player? (I guess yes)
And is this true even when I do the same but replace `world_viz.mp4` with `world.mp4`? (I guess no)

**Comment by papr** [comment]
Your guesses are both correct.
